# name: Lint

# on: [
#     push,
#     pull_request
# ]

# jobs:
#     lint:
#         runs-on: ubuntu-latest

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js
#               uses: actions/setup-node@v2
#               with:
#                   node-version: '14'
            
#             - name: Install ESLint
#               run: npm install eslint --save-dev
            
#             - name: Run ESLint
#               run: npx eslint .

#             - name: Install pipeline-linter-cli
#               run: npm install -g @technosophos/pipeline-linter-cli

#             - name: Run pipeline-linter
#               run: |
#                     if [ -f ../../Jenkinsfile ]; then
#                         pipeline-linter ../../Jenkinsfile
#                     else
#                         echo "No Jenkinsfile found"
#                     fi